export const photoPrompts: Record<string, string[]> = {
  WORKOUT: [
    "Show us your gym fit.",
    "Show us the weights you used.",
    "Show us the equipment.",
    "Show off your gym shoes.",
    "Capture the setup.",
    "Show us the rack.",
    "What does your gym look like today?",
    "Show us where you train.",
    "Show us your grip.",
    "Before the first set.",
    "Show us the bar.",
    "What are you working with today?",
    "Show us the view from the platform.",
    "Post-session — show us the sweat.",
    "Show us what you brought today.",
  ],
  MEAL: [
    "Show us the plate.",
    "Show us how it's made.",
    "Close-up on the detail.",
    "Show us what good looks like.",
    "Show us the prep.",
    "Show us the ingredients.",
    "What does it actually look like?",
    "Show us the portion.",
    "Show us the bowl.",
    "Natural light, if you have it.",
  ],
  WELLNESS: [
    "Show us the space.",
    "Show us your setup.",
    "Capture the moment.",
    "Show us what recovery looks like.",
    "Show us the ritual.",
    "Show us the temperature.",
    "Show us where you go to reset.",
    "Show us the morning light.",
    "Show us what quiet looks like.",
    "Show us the routine.",
  ],
  GENERAL: [
    "Add a photo.",
    "Show us.",
    "A picture says more.",
    "Show us where you are.",
    "What does today look like?",
  ],
};
